
  
version:  '3.7'
services:
   nginx:
     image: nginx:1.15.3-alpine
     restart: on-failure
     volumes:
       - './public/:/usr/src/app'
       - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
     ports:
       - "8000:80"
     depends_on:
       - php
   php:
     build:
       context: .
       dockerfile: Dockerfile
     restart: on-failure
     volumes:
       - '.:/usr/src/app'